# Script to parse the LMDB headers and generate Julia wrappers.
#
# Usage: julia --project=res res/wrap.jl

using Clang
using Clang.Generators

using JuliaFormatter

using LMDB_jll

function main()
    cd(@__DIR__) do
        include_dir = joinpath(LMDB_jll.artifact_dir, "include") |> normpath

        args = get_default_args()
        push!(args, "-isystem$include_dir")

        options = load_options(joinpath(@__DIR__, "lmdb.toml"))

        headers = [joinpath(include_dir, "lmdb.h")]

        ctx = create_context(headers, args, options)

        build!(ctx)

        output_file = options["general"]["output_file_path"]

        # prepend "autogenerated, do not edit!" comment
        output_data = read(output_file, String)
        open(output_file, "w") do io
            println(io, """# This file is automatically generated. Do not edit!
                           # To re-generate, execute res/wrap.jl""")
            println(io)
            print(io, output_data)
        end

        format_file(output_file, YASStyle())
    end

    return
end

isinteractive() || main()
