# Script to parse the LMDB headers and generate Julia wrappers.
#
# Usage: julia --project=res res/wrap.jl

using Clang
using Clang.Generators

using JuliaFormatter

using LMDB_jll

# Tier-1 bindings whose return type is `Cint` but is **not** an LMDB status
# code. The `@checked` post-processor leaves these alone so callers don't get
# spurious throws.
const UNCHECKED_CINT = (
    "mdb_env_get_maxkeysize",  # returns the maximum key size, not a status.
    "mdb_cmp",                  # returns the comparison result (-1/0/1).
    "mdb_dcmp",                 # idem for dup-data.
)

# Replace `function $name(args)\n    @ccall ...::Cint\nend` with
# `@checked function ...`. Hand-applied annotations are stable across regens
# because the regex anchors on the auto-generated layout.
function postprocess!(path::AbstractString)
    src = read(path, String)
    re = r"^(?<indent>[ \t]*)function\s+(?<name>mdb_[A-Za-z0-9_]+)(?<rest>\([^\)]*\)\s*\n(?:.*\n)*?\1end\b)"m
    out = IOBuffer()
    last = 1
    for m in eachmatch(re, src)
        write(out, SubString(src, last, m.offset - 1))
        body = SubString(src, m.offset, m.offset + length(m.match) - 1)
        # Only @checked-wrap status-returning bindings, identified by `::Cint`
        # in the @ccall return-type slot.
        if m[:name] ∉ UNCHECKED_CINT && occursin(r"\)::Cint\s*\n", body)
            write(out, m[:indent])
            write(out, "@checked ")
            write(out, SubString(body, length(m[:indent]) + 1))
        else
            write(out, body)
        end
        last = m.offset + length(m.match)
    end
    write(out, SubString(src, last, lastindex(src)))
    write(path, String(take!(out)))
end

function main()
    cd(@__DIR__) do
        include_dir = joinpath(LMDB_jll.artifact_dir, "include") |> normpath

        args = get_default_args()
        push!(args, "-isystem$include_dir")

        options = load_options(joinpath(@__DIR__, "lmdb.toml"))

        headers = [joinpath(include_dir, "lmdb.h")]

        ctx = create_context(headers, args, options)

        build!(ctx)

        output_file = options["general"]["output_file_path"]

        # Annotate status-returning bindings with `@checked`.
        postprocess!(output_file)

        # prepend "autogenerated, do not edit!" comment
        output_data = read(output_file, String)
        open(output_file, "w") do io
            println(io, """# This file is automatically generated. Do not edit!
                           # To re-generate, execute res/wrap.jl""")
            println(io)
            print(io, output_data)
        end

        format_file(output_file, YASStyle())
    end

    return
end

isinteractive() || main()
