# This file is automatically generated. Do not edit!
# To re-generate, execute res/wrap.jl

using LMDB_jll
export LMDB_jll

using CEnum: CEnum, @cenum

const __mode_t = Cuint

const mode_t = __mode_t

mutable struct MDB_txn end

const MDB_dbi = Cuint

function mdb_dbi_open(txn, name, flags, dbi)
    @ccall liblmdb.mdb_dbi_open(txn::Ptr{MDB_txn}, name::Cstring, flags::Cuint,
                                dbi::Ptr{MDB_dbi})::Cint
end

mutable struct MDB_env end

function mdb_dbi_close(env, dbi)
    @ccall liblmdb.mdb_dbi_close(env::Ptr{MDB_env}, dbi::MDB_dbi)::Cvoid
end

const mdb_mode_t = mode_t

const mdb_filehandle_t = Cint

mutable struct MDB_cursor end

struct MDB_val
    mv_size::Csize_t
    mv_data::Ptr{Cvoid}
end

# typedef int ( MDB_cmp_func ) ( const MDB_val * a , const MDB_val * b )
const MDB_cmp_func = Cvoid

# typedef void ( MDB_rel_func ) ( MDB_val * item , void * oldptr , void * newptr , void * relctx )
const MDB_rel_func = Cvoid

@cenum MDB_cursor_op::UInt32 begin
    MDB_FIRST = 0
    MDB_FIRST_DUP = 1
    MDB_GET_BOTH = 2
    MDB_GET_BOTH_RANGE = 3
    MDB_GET_CURRENT = 4
    MDB_GET_MULTIPLE = 5
    MDB_LAST = 6
    MDB_LAST_DUP = 7
    MDB_NEXT = 8
    MDB_NEXT_DUP = 9
    MDB_NEXT_MULTIPLE = 10
    MDB_NEXT_NODUP = 11
    MDB_PREV = 12
    MDB_PREV_DUP = 13
    MDB_PREV_NODUP = 14
    MDB_SET = 15
    MDB_SET_KEY = 16
    MDB_SET_RANGE = 17
    MDB_PREV_MULTIPLE = 18
end

struct MDB_stat
    ms_psize::Cuint
    ms_depth::Cuint
    ms_branch_pages::Csize_t
    ms_leaf_pages::Csize_t
    ms_overflow_pages::Csize_t
    ms_entries::Csize_t
end

struct MDB_envinfo
    me_mapaddr::Ptr{Cvoid}
    me_mapsize::Csize_t
    me_last_pgno::Csize_t
    me_last_txnid::Csize_t
    me_maxreaders::Cuint
    me_numreaders::Cuint
end

function mdb_version(major, minor, patch)
    @ccall liblmdb.mdb_version(major::Ptr{Cint}, minor::Ptr{Cint},
                               patch::Ptr{Cint})::Cstring
end

function mdb_strerror(err)
    @ccall liblmdb.mdb_strerror(err::Cint)::Cstring
end

function mdb_env_create(env)
    @ccall liblmdb.mdb_env_create(env::Ptr{Ptr{MDB_env}})::Cint
end

function mdb_env_open(env, path, flags, mode)
    @ccall liblmdb.mdb_env_open(env::Ptr{MDB_env}, path::Cstring, flags::Cuint,
                                mode::mdb_mode_t)::Cint
end

function mdb_env_copy(env, path)
    @ccall liblmdb.mdb_env_copy(env::Ptr{MDB_env}, path::Cstring)::Cint
end

function mdb_env_copyfd(env, fd)
    @ccall liblmdb.mdb_env_copyfd(env::Ptr{MDB_env}, fd::mdb_filehandle_t)::Cint
end

function mdb_env_copy2(env, path, flags)
    @ccall liblmdb.mdb_env_copy2(env::Ptr{MDB_env}, path::Cstring, flags::Cuint)::Cint
end

function mdb_env_copyfd2(env, fd, flags)
    @ccall liblmdb.mdb_env_copyfd2(env::Ptr{MDB_env}, fd::mdb_filehandle_t,
                                   flags::Cuint)::Cint
end

function mdb_env_stat(env, stat)
    @ccall liblmdb.mdb_env_stat(env::Ptr{MDB_env}, stat::Ptr{MDB_stat})::Cint
end

function mdb_env_info(env, stat)
    @ccall liblmdb.mdb_env_info(env::Ptr{MDB_env}, stat::Ptr{MDB_envinfo})::Cint
end

function mdb_env_sync(env, force)
    @ccall liblmdb.mdb_env_sync(env::Ptr{MDB_env}, force::Cint)::Cint
end

function mdb_env_close(env)
    @ccall liblmdb.mdb_env_close(env::Ptr{MDB_env})::Cvoid
end

function mdb_env_set_flags(env, flags, onoff)
    @ccall liblmdb.mdb_env_set_flags(env::Ptr{MDB_env}, flags::Cuint, onoff::Cint)::Cint
end

function mdb_env_get_flags(env, flags)
    @ccall liblmdb.mdb_env_get_flags(env::Ptr{MDB_env}, flags::Ptr{Cuint})::Cint
end

function mdb_env_get_path(env, path)
    @ccall liblmdb.mdb_env_get_path(env::Ptr{MDB_env}, path::Ptr{Cstring})::Cint
end

function mdb_env_get_fd(env, fd)
    @ccall liblmdb.mdb_env_get_fd(env::Ptr{MDB_env}, fd::Ptr{mdb_filehandle_t})::Cint
end

function mdb_env_set_mapsize(env, size)
    @ccall liblmdb.mdb_env_set_mapsize(env::Ptr{MDB_env}, size::Csize_t)::Cint
end

function mdb_env_set_maxreaders(env, readers)
    @ccall liblmdb.mdb_env_set_maxreaders(env::Ptr{MDB_env}, readers::Cuint)::Cint
end

function mdb_env_get_maxreaders(env, readers)
    @ccall liblmdb.mdb_env_get_maxreaders(env::Ptr{MDB_env}, readers::Ptr{Cuint})::Cint
end

function mdb_env_set_maxdbs(env, dbs)
    @ccall liblmdb.mdb_env_set_maxdbs(env::Ptr{MDB_env}, dbs::MDB_dbi)::Cint
end

function mdb_env_get_maxkeysize(env)
    @ccall liblmdb.mdb_env_get_maxkeysize(env::Ptr{MDB_env})::Cint
end

function mdb_env_set_userctx(env, ctx)
    @ccall liblmdb.mdb_env_set_userctx(env::Ptr{MDB_env}, ctx::Ptr{Cvoid})::Cint
end

function mdb_env_get_userctx(env)
    @ccall liblmdb.mdb_env_get_userctx(env::Ptr{MDB_env})::Ptr{Cvoid}
end

# typedef void MDB_assert_func ( MDB_env * env , const char * msg )
const MDB_assert_func = Cvoid

function mdb_env_set_assert(env, func)
    @ccall liblmdb.mdb_env_set_assert(env::Ptr{MDB_env}, func::Ptr{MDB_assert_func})::Cint
end

function mdb_txn_begin(env, parent, flags, txn)
    @ccall liblmdb.mdb_txn_begin(env::Ptr{MDB_env}, parent::Ptr{MDB_txn}, flags::Cuint,
                                 txn::Ptr{Ptr{MDB_txn}})::Cint
end

function mdb_txn_env(txn)
    @ccall liblmdb.mdb_txn_env(txn::Ptr{MDB_txn})::Ptr{MDB_env}
end

function mdb_txn_id(txn)
    @ccall liblmdb.mdb_txn_id(txn::Ptr{MDB_txn})::Csize_t
end

function mdb_txn_commit(txn)
    @ccall liblmdb.mdb_txn_commit(txn::Ptr{MDB_txn})::Cint
end

function mdb_txn_abort(txn)
    @ccall liblmdb.mdb_txn_abort(txn::Ptr{MDB_txn})::Cvoid
end

function mdb_txn_reset(txn)
    @ccall liblmdb.mdb_txn_reset(txn::Ptr{MDB_txn})::Cvoid
end

function mdb_txn_renew(txn)
    @ccall liblmdb.mdb_txn_renew(txn::Ptr{MDB_txn})::Cint
end

function mdb_stat(txn, dbi, stat)
    @ccall liblmdb.mdb_stat(txn::Ptr{MDB_txn}, dbi::MDB_dbi, stat::Ptr{MDB_stat})::Cint
end

function mdb_dbi_flags(txn, dbi, flags)
    @ccall liblmdb.mdb_dbi_flags(txn::Ptr{MDB_txn}, dbi::MDB_dbi, flags::Ptr{Cuint})::Cint
end

function mdb_drop(txn, dbi, del)
    @ccall liblmdb.mdb_drop(txn::Ptr{MDB_txn}, dbi::MDB_dbi, del::Cint)::Cint
end

function mdb_set_compare(txn, dbi, cmp)
    @ccall liblmdb.mdb_set_compare(txn::Ptr{MDB_txn}, dbi::MDB_dbi,
                                   cmp::Ptr{MDB_cmp_func})::Cint
end

function mdb_set_dupsort(txn, dbi, cmp)
    @ccall liblmdb.mdb_set_dupsort(txn::Ptr{MDB_txn}, dbi::MDB_dbi,
                                   cmp::Ptr{MDB_cmp_func})::Cint
end

function mdb_set_relfunc(txn, dbi, rel)
    @ccall liblmdb.mdb_set_relfunc(txn::Ptr{MDB_txn}, dbi::MDB_dbi,
                                   rel::Ptr{MDB_rel_func})::Cint
end

function mdb_set_relctx(txn, dbi, ctx)
    @ccall liblmdb.mdb_set_relctx(txn::Ptr{MDB_txn}, dbi::MDB_dbi, ctx::Ptr{Cvoid})::Cint
end

function mdb_get(txn, dbi, key, data)
    @ccall liblmdb.mdb_get(txn::Ptr{MDB_txn}, dbi::MDB_dbi, key::Ptr{MDB_val},
                           data::Ptr{MDB_val})::Cint
end

function mdb_put(txn, dbi, key, data, flags)
    @ccall liblmdb.mdb_put(txn::Ptr{MDB_txn}, dbi::MDB_dbi, key::Ptr{MDB_val},
                           data::Ptr{MDB_val}, flags::Cuint)::Cint
end

function mdb_del(txn, dbi, key, data)
    @ccall liblmdb.mdb_del(txn::Ptr{MDB_txn}, dbi::MDB_dbi, key::Ptr{MDB_val},
                           data::Ptr{MDB_val})::Cint
end

function mdb_cursor_open(txn, dbi, cursor)
    @ccall liblmdb.mdb_cursor_open(txn::Ptr{MDB_txn}, dbi::MDB_dbi,
                                   cursor::Ptr{Ptr{MDB_cursor}})::Cint
end

function mdb_cursor_close(cursor)
    @ccall liblmdb.mdb_cursor_close(cursor::Ptr{MDB_cursor})::Cvoid
end

function mdb_cursor_renew(txn, cursor)
    @ccall liblmdb.mdb_cursor_renew(txn::Ptr{MDB_txn}, cursor::Ptr{MDB_cursor})::Cint
end

function mdb_cursor_txn(cursor)
    @ccall liblmdb.mdb_cursor_txn(cursor::Ptr{MDB_cursor})::Ptr{MDB_txn}
end

function mdb_cursor_dbi(cursor)
    @ccall liblmdb.mdb_cursor_dbi(cursor::Ptr{MDB_cursor})::MDB_dbi
end

function mdb_cursor_get(cursor, key, data, op)
    @ccall liblmdb.mdb_cursor_get(cursor::Ptr{MDB_cursor}, key::Ptr{MDB_val},
                                  data::Ptr{MDB_val}, op::MDB_cursor_op)::Cint
end

function mdb_cursor_put(cursor, key, data, flags)
    @ccall liblmdb.mdb_cursor_put(cursor::Ptr{MDB_cursor}, key::Ptr{MDB_val},
                                  data::Ptr{MDB_val}, flags::Cuint)::Cint
end

function mdb_cursor_del(cursor, flags)
    @ccall liblmdb.mdb_cursor_del(cursor::Ptr{MDB_cursor}, flags::Cuint)::Cint
end

function mdb_cursor_count(cursor, countp)
    @ccall liblmdb.mdb_cursor_count(cursor::Ptr{MDB_cursor}, countp::Ptr{Csize_t})::Cint
end

function mdb_cmp(txn, dbi, a, b)
    @ccall liblmdb.mdb_cmp(txn::Ptr{MDB_txn}, dbi::MDB_dbi, a::Ptr{MDB_val},
                           b::Ptr{MDB_val})::Cint
end

function mdb_dcmp(txn, dbi, a, b)
    @ccall liblmdb.mdb_dcmp(txn::Ptr{MDB_txn}, dbi::MDB_dbi, a::Ptr{MDB_val},
                            b::Ptr{MDB_val})::Cint
end

# typedef int ( MDB_msg_func ) ( const char * msg , void * ctx )
const MDB_msg_func = Cvoid

function mdb_reader_list(env, func, ctx)
    @ccall liblmdb.mdb_reader_list(env::Ptr{MDB_env}, func::Ptr{MDB_msg_func},
                                   ctx::Ptr{Cvoid})::Cint
end

function mdb_reader_check(env, dead)
    @ccall liblmdb.mdb_reader_check(env::Ptr{MDB_env}, dead::Ptr{Cint})::Cint
end

const MDB_VERSION_MAJOR = 0

const MDB_VERSION_MINOR = 9

const MDB_VERSION_PATCH = 33

const MDB_VERSION_DATE = "May 21, 2024"

const MDB_FIXEDMAP = 0x01

const MDB_NOSUBDIR = 0x4000

const MDB_NOSYNC = 0x00010000

const MDB_RDONLY = 0x00020000

const MDB_NOMETASYNC = 0x00040000

const MDB_WRITEMAP = 0x00080000

const MDB_MAPASYNC = 0x00100000

const MDB_NOTLS = 0x00200000

const MDB_NOLOCK = 0x00400000

const MDB_NORDAHEAD = 0x00800000

const MDB_NOMEMINIT = 0x01000000

const MDB_REVERSEKEY = 0x02

const MDB_DUPSORT = 0x04

const MDB_INTEGERKEY = 0x08

const MDB_DUPFIXED = 0x10

const MDB_INTEGERDUP = 0x20

const MDB_REVERSEDUP = 0x40

const MDB_CREATE = 0x00040000

const MDB_NOOVERWRITE = 0x10

const MDB_NODUPDATA = 0x20

const MDB_CURRENT = 0x40

const MDB_RESERVE = 0x00010000

const MDB_APPEND = 0x00020000

const MDB_APPENDDUP = 0x00040000

const MDB_MULTIPLE = 0x00080000

const MDB_CP_COMPACT = 0x01

const MDB_SUCCESS = 0

const MDB_KEYEXIST = -30799

const MDB_NOTFOUND = -30798

const MDB_PAGE_NOTFOUND = -30797

const MDB_CORRUPTED = -30796

const MDB_PANIC = -30795

const MDB_VERSION_MISMATCH = -30794

const MDB_INVALID = -30793

const MDB_MAP_FULL = -30792

const MDB_DBS_FULL = -30791

const MDB_READERS_FULL = -30790

const MDB_TLS_FULL = -30789

const MDB_TXN_FULL = -30788

const MDB_CURSOR_FULL = -30787

const MDB_PAGE_FULL = -30786

const MDB_MAP_RESIZED = -30785

const MDB_INCOMPATIBLE = -30784

const MDB_BAD_RSLOT = -30783

const MDB_BAD_TXN = -30782

const MDB_BAD_VALSIZE = -30781

const MDB_BAD_DBI = -30780

const MDB_LAST_ERRCODE = MDB_BAD_DBI
